MONGODB:
  # Complete mongodb uri with authentication and arguments will be appended to uri as query parameters
  URI: "mongodb://localhost:27017"
  ARGUMENTS: ""
  DATABASE: "campaigns"
JWT:
  EXPIRY_TIME: 86400  # In seconds, default 24 hours
  SECRET: "iLFwO0exwQTwJUBdgaGGRKt3T"
DOCKER:
  MANAGER_URL:
  AUTHENTICATION_KEY:

